### Get license list
GET localhost:8001/licenses

<> 2024-11-28T161750.200.json

### Register User Request
POST http://localhost:8001/auth/register
Content-Type: application/json

{
  "email": "useasdr@examasdpleasd.com",
  "password": "securepassword123"
}

### Login User Request
POST http://localhost:8001/auth/login
Content-Type: application/json

{
  "email": "useasdr@examasdpleasd.com",
  "password": "securepassword123"
}

### Refresh token Request
POST http://localhost:8001/auth/refresh
Content-Type: application/json

{
  "refresh_token" : "test"
}

### Movie list
GET http://localhost:8001/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzM1MjU4ODIsImlhdCI6MTczMzQzOTQ4MiwidXNlcl9pZCI6MX0.xuCQSK_ySXW5hD-2b_awv2Qk43iSrftBUQbBnVKj8s