// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserLicenseRepository is an autogenerated mock type for the UserLicenseRepository type
type UserLicenseRepository struct {
	mock.Mock
}

// CheckIfUserHasActiveLicense provides a mock function with given fields: userID
func (_m *UserLicenseRepository) CheckIfUserHasActiveLicense(userID int64) (bool, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for CheckIfUserHasActiveLicense")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (bool, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int64) bool); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUserLicense provides a mock function with given fields: licenseID, userID
func (_m *UserLicenseRepository) CreateUserLicense(licenseID int64, userID int64) (bool, error) {
	ret := _m.Called(licenseID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserLicense")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int64) (bool, error)); ok {
		return rf(licenseID, userID)
	}
	if rf, ok := ret.Get(0).(func(int64, int64) bool); ok {
		r0 = rf(licenseID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = rf(licenseID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserLicenseRepository creates a new instance of UserLicenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserLicenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserLicenseRepository {
	mock := &UserLicenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
